avance2/controlmedico/controlmedico/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include('core.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
]

avance2/controlmedico/core/urls.py
from django.urls import path
from . import views
from .views import CreateMedico, ListMedico


app_name = 'core' 

urlpatterns = [
    # URLs para Puesto
    path('puesto/create/', views.CreatePuesto.as_view(), name='create_puesto'),
    path('puesto/list/', views.ListPuesto.as_view(), name='list_puesto'),
    path('puesto/<int:pk>/', views.DetailPuesto.as_view(), name='detail_puesto'),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name='update_puesto'),
    path('puesto/<int:pk>/delete/', views.DeletePuesto.as_view(), name='delete_puesto'),

    # URLs para Empleado
    path('empleado/create/', views.CreateEmpleado.as_view(), name='create_empleado'),
    path('empleado/list/', views.ListEmpleado.as_view(), name='list_empleado'),
    path('empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='detail_empleado'),
    path('empleado/<int:pk>/update/', views.UpdateEmpleado.as_view(), name='update_empleado'),
    path('empleado/<int:pk>/delete/', views.DeleteEmpleado.as_view(), name='delete_empleado'),

    # URLs para Alergia
    path('alergia/create/', views.CreateAlergia.as_view(), name='create_alergia'),
    path('alergia/list/', views.ListAlergia.as_view(), name='list_alergia'),
    path('alergia/<int:pk>/', views.DetailAlergia.as_view(), name='detail_alergia'),
    path('alergia/<int:pk>/update/', views.UpdateAlergia.as_view(), name='update_alergia'),
    path('alergia/<int:pk>/delete/', views.DeleteAlergia.as_view(), name='delete_alergia'),

    # URLs para Departamento
    path('departamento/create/', views.CreateDepartamento.as_view(), name='create_departamento'),
    path('departamento/list/', views.ListDepartamento.as_view(), name='list_departamento'),
    path('departamento/<int:pk>/', views.DetailDepartamento.as_view(), name='detail_departamento'),
    path('departamento/<int:pk>/update/', views.UpdateDepartamento.as_view(), name='update_departamento'),
    path('departamento/<int:pk>/delete/', views.DeleteDepartamento.as_view(), name='delete_departamento'),

    # URLs para Medicamento
    path('medicamento/create/', views.CreateMedicamento.as_view(), name='create_medicamento'),
    path('medicamento/list/', views.ListMedicamento.as_view(), name='list_medicamento'),
    path('medicamento/<int:pk>/', views.DetailMedicamento.as_view(), name='detail_medicamento'),
    path('medicamento/<int:pk>/update/', views.UpdateMedicamento.as_view(), name='update_medicamento'),
    path('medicamento/<int:pk>/delete/', views.DeleteMedicamento.as_view(), name='delete_medicamento'),
    
    # URLs para Suministro
    path('suministro/create/', views.CreateSuministro.as_view(), name='create_suministro'),
    path('suministro/list/', views.ListSuministro.as_view(), name='list_suministro'),
    path('suministro/<int:pk>/', views.DetailSuministro.as_view(), name='detail_suministro'),
    path('suministro/<int:pk>/update/', views.UpdateSuministro.as_view(), name='update_suministro'),
    path('suministro/<int:pk>/delete/', views.DeleteSuministro.as_view(), name='delete_suministro'),

    # URLs para Medico
    path('medico/create/', views.CreateMedico.as_view(), name='create_medico'),
    path('medico/list/', views.ListMedico.as_view(), name='list_medico'),
    path('medico/<int:pk>/', views.DetailMedico.as_view(), name='detail_medico'),
    path('medico/<int:pk>/update/', views.UpdateMedico.as_view(), name='update_medico'),
    path('medico/<int:pk>/delete/', views.DeleteMedico.as_view(), name='delete_medico'),

    # URLs para Consulta
    path('consulta/create/', views.CreateConsulta.as_view(), name='create_consulta'),
    path('consulta/list/', views.ListConsulta.as_view(), name='list_consulta'),
    path('consulta/<int:pk>/', views.DetailConsulta.as_view(), name='detail_consulta'),
    path('consulta/<int:pk>/update/', views.UpdateConsulta.as_view(), name='update_consulta'),
    path('consulta/<int:pk>/delete/', views.DeleteConsulta.as_view(), name='delete_consulta'),
    
    # URLs para EfectosSecundarios
    path('efectos_secundarios/create/', views.CreateEfectosSecundarios.as_view(), name='create_efectos_secundarios'),
    path('efectos_secundarios/list/', views.ListEfectosSecundarios.as_view(), name='list_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/', views.DetailEfectosSecundarios.as_view(), name='detail_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/update/', views.UpdateEfectosSecundarios.as_view(), name='update_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/delete/', views.DeleteEfectosSecundarios.as_view(), name='delete_efectos_secundarios'),

    # URLs para Contraindicacion
    path('contraindicacion/create/', views.CreateContraindicacion.as_view(), name='create_contraindicacion'),
    path('contraindicacion/list/', views.ListContraindicacion.as_view(), name='list_contraindicacion'),
    path('contraindicacion/<int:pk>/', views.DetailContraindicacion.as_view(), name='detail_contraindicacion'),
    path('contraindicacion/<int:pk>/update/', views.UpdateContraindicacion.as_view(), name='update_contraindicacion'),
    path('contraindicacion/<int:pk>/delete/', views.DeleteContraindicacion.as_view(), name='delete_contraindicacion'),
    # URLs para FormaAdministracion
    path('forma_administracion/create/', views.CreateFormaAdministracion.as_view(), name='create_forma_administracion'),
    path('forma_administracion/list/', views.ListFormaAdministracion.as_view(), name='list_forma_administracion'),
    path('forma_administracion/<int:pk>/', views.DetailFormaAdministracion.as_view(), name='detail_forma_administracion'),
    path('forma_administracion/<int:pk>/update/', views.UpdateFormaAdministracion.as_view(), name='update_forma_administracion'),
    path('forma_administracion/<int:pk>/delete/', views.DeleteFormaAdministracion.as_view(), name='delete_forma_administracion'),

    # URLs para AlergiaEmpleado
    path('alergiaempleado/create/', views.CreateAlergiaEmpleado.as_view(), name='create_alergiaempleado'),
    path('alergiaempleado/list/', views.ListAlergiaEmpleado.as_view(), name='list_alergiaempleado'),
    path('alergiaempleado/<int:pk>/', views.DetailAlergiaEmpleado.as_view(), name='detail_alergiaempleado'),
    path('alergiaempleado/<int:pk>/update/', views.UpdateAlergiaEmpleado.as_view(), name='update_alergiaempleado'),
    path('alergiaempleado/<int:pk>/delete/', views.DeleteAlergiaEmpleado.as_view(), name='delete_alergiaempleado'),

    # URLs para MediEfecSecu
    path('medi_efec_secu/create/', views.CreateMediEfecSecu.as_view(), name='create_medi_efec_secu'),
    path('medi_efec_secu/list/', views.ListMediEfecSecu.as_view(), name='list_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/', views.DetailMediEfecSecu.as_view(), name='detail_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/update/', views.UpdateMediEfecSecu.as_view(), name='update_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/delete/', views.DeleteMediEfecSecu.as_view(), name='delete_medi_efec_secu'),

    # URLs para MediContra
    path('medi_contra/create/', views.CreateMediContra.as_view(), name='create_medi_contra'),
    path('medi_contra/list/', views.ListMediContra.as_view(), name='list_medi_contra'),
    path('medi_contra/<int:pk>/', views.DetailMediContra.as_view(), name='detail_medi_contra'),
    path('medi_contra/<int:pk>/update/', views.UpdateMediContra.as_view(), name='update_medi_contra'),
    path('medi_contra/<int:pk>/delete/', views.DeleteMediContra.as_view(), name='delete_medi_contra'),

    # URLs para MediFormaAdmi
    path('medi_forma_admi/create/', views.CreateMediFormaAdmi.as_view(), name='create_medi_forma_admi'),
    path('medi_forma_admi/list/', views.ListMediFormaAdmi.as_view(), name='list_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/', views.DetailMediFormaAdmi.as_view(), name='detail_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/update/', views.UpdateMediFormaAdmi.as_view(), name='update_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/delete/', views.DeleteMediFormaAdmi.as_view(), name='delete_medi_forma_admi'),

    # URLs para SuministroConsulta
    path('suministro_consulta/create/', views.CreateSuministroConsulta.as_view(), name='create_suministro_consulta'),
    path('suministro_consulta/list/', views.ListSuministroConsulta.as_view(), name='list_suministro_consulta'),
    path('suministro_consulta/<int:pk>/', views.DetailSuministroConsulta.as_view(), name='detail_suministro_consulta'),
    path('suministro_consulta/<int:pk>/update/', views.UpdateSuministroConsulta.as_view(), name='update_suministro_consulta'),
    path('suministro_consulta/<int:pk>/delete/', views.DeleteSuministroConsulta.as_view(), name='delete_suministro_consulta'),

    # URLs para MedicamentoConsulta
    path('medicamento_consulta/create/', views.CreateMedicamentoConsulta.as_view(), name='create_medicamento_consulta'),
    path('medicamento_consulta/list/', views.ListMedicamentoConsulta.as_view(), name='list_medicamento_consulta'),
    path('medicamento_consulta/<int:pk>/', views.DetailMedicamentoConsulta.as_view(), name='detail_medicamento_consulta'),
    path('medicamento_consulta/<int:pk>/update/', views.UpdateMedicamentoConsulta.as_view(), name='update_medicamento_consulta'),
    path('medicamento_consulta/<int:pk>/delete/', views.DeleteMedicamentoConsulta.as_view(), name='delete_medicamento_consulta'),
]
 

avance2/controlmedico/core/forms.py
from django.utils import timezone
from django import forms
from .models import Puesto, Empleado, Alergia, Departamento, Medicamento, AlergiaEmpleado
from .models import Suministro, Medico, Consulta, EfectosSecundarios, Contraindicacion, FormaAdministracion, MediEfecSecu
from .models import MediContra, MediFormaAdmi, SuministroConsulta, MedicamentoConsulta
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm

class PuestoForm(forms.ModelForm):
    class Meta:
        model = Puesto
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del puesto'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del puesto'}),
        }

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = ['noempleado', 'nombrePila', 'apPat', 'apMat', 'fnacimiento', 'puesto', 'departamento']
        widgets = {
            'noempleado': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número de empleado'}),
            'nombrePila': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del empleado'}),
            'apPat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido paterno'}),
            'apMat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido materno'}),
            'fnacimiento': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'puesto': forms.Select(attrs={'class': 'form-control'}),
            'departamento': forms.Select(attrs={'class': 'form-control'}),
        }

class AlergiaForm(forms.ModelForm):
    class Meta:
        model = Alergia
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la alergia'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción de la alergia'}),
        }

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Departamento'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del Departamento'}),
        }
        
class MedicamentoForm(forms.ModelForm):
    class Meta:
        model = Medicamento
        fields = ['nombre', 'descripcion', 'dosis', 'stock']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del medicamento'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del medicamento'}),
            'dosis': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Dosis del medicamento'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Stock del medicamento'}),
        }
        
class SuministroForm(forms.ModelForm):
    class Meta:
        model = Suministro
        fields = ['nombre', 'descripcion', 'stock']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del suministro'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del suministro'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Stock del suministro'}),
        }
        
class MedicoForm(forms.ModelForm):
    class Meta:
        model = Medico
        fields = ['nombrePila', 'apPat', 'apMat', 'cedula', 'numTel']
        widgets = {
            'nombrePila': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del médico'}),
            'apPat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido paterno'}),
            'apMat': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido materno'}),
            'cedula': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número de cédula'}),
            'numTel': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Número de teléfono'}),
        }
         
class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = ['motivo', 'sintomas', 'peso', 'altura', 'diagnostico', 'empleado', 'medicamentos', 'suministros']
        widgets = {
            'motivo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Motivo de la consulta'}),
            'sintomas': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Síntomas'}),
            'peso': forms.NumberInput(attrs={'class': 'form-control'}),
            'altura': forms.NumberInput(attrs={'class': 'form-control'}),
            'diagnostico': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Diagnóstico'}),
            'empleado': forms.Select(attrs={'class': 'form-control'}),
            'medicamentos': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'suministros': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['medicamentos'].required = False
            
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['suministros'].required = False
        
class EfectosSecundariosForm(forms.ModelForm):
    class Meta:
        model = EfectosSecundarios
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Efecto Secundario'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del Efecto Secundario'}),
        }
        
class ContraindicacionForm(forms.ModelForm):
    class Meta:
        model = Contraindicacion
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la Contraindicación'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción de la Contraindicación'}),
        }

class FormaAdministracionForm(forms.ModelForm):
    class Meta:
        model = FormaAdministracion
        fields = ['nombre', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la Forma de Administración'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción de la Forma de Administración'}),
        }

class AlergiaEmpleadoForm(forms.ModelForm):
    class Meta:
        model = AlergiaEmpleado
        fields = ['alergia', 'empleado']
        widgets = {
            'alergia': forms.Select(attrs={'class': 'form-control'}),
            'empleado': forms.Select(attrs={'class': 'form-control'}),
        }

class MediEfecSecuForm(forms.ModelForm):
    class Meta:
        model = MediEfecSecu
        fields = ['medicamento', 'efectosSecundarios']
        

class MediContraForm(forms.ModelForm):
    class Meta:
        model = MediContra
        fields = ['medicamento', 'contraindicaciones']

class MediFormaAdmiForm(forms.ModelForm):
    class Meta:
        model = MediFormaAdmi
        fields = ['medicamento', 'formaAdministracion']
        
class SuministroConsultaForm(forms.ModelForm):
    class Meta:
        model = SuministroConsulta
        fields = ['suministro', 'consulta', 'cantidad']


class MedicamentoConsultaForm(forms.ModelForm):
    class Meta:
        model = MedicamentoConsulta
        fields = ['medicamento', 'consulta', 'cantidad']

avance2/controlmedico/core/templates/core/create_contraindicacion.html
{% extends "base/base.html" %}

{% block title %}
  Crear Contraindicación
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Crear</button>
    <a href="{% url 'core:list_contraindicacion' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/create_medi_forma_admi.html
{% extends "base/base.html" %}

{% block title %}
  Crear MediFormaAdmi
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_medi_forma_admi' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/create_medicamento.html
{% extends "base/base.html" %}

{% block title %}
  Crear medicamento
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_medicamento' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/create_medicamento_consulta.html
{% extends "base/base.html" %}

{% block title %}
  Crear MedicamentoConsulta
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_medicamento_consulta' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/create_medico.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Registrar Médico</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
    </form>
{% endblock %}

avance2/controlmedico/core/templates/core/create_suministro_consulta.html
{% extends "base/base.html" %}

{% block title %}
  Crear SuministroConsulta
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'core:list_suministro_consulta' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/delete_consulta.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar consulta
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar la consulta '{{ consulta.id }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_consulta' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/delete_contraindicacion.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Contraindicación
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar la Contraindicación '{{ contraindicacion.nombre }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_contraindicacion' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/delete_empleado.html
{% extends "base/base.html" %}

{% block title %}
  Eliminar Empleado
{% endblock title %}

{% block content %}
  <p>¿Estás seguro de que deseas eliminar al Empleado '{{ empleado.id }}'?</p>
  <form action="" method="post" class="form">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a href="{% url 'core:list_empleado' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_alergia.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Alergias
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_alergia' %}" class="btn btn-success">Crear alergia</a>
      {% for alergia in Alergias %}
        <tr>
          <td>{{ alergia.id }}</td>
          <td>{{ alergia.nombre }}</td>
          <td>{{ alergia.descripcion }}</td>
          <td>
            <a href="{% url 'core:detail_alergia' alergia.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_alergia' alergia.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_alergia' alergia.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_medi_efec_secu.html
{% extends "base/base.html" %}

{% block title %}
  Lista de MediEfecSecus
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Medicamento</th>
      <th>Efectos Secundarios</th>
      <th>Descripcion</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_medi_efec_secu' %}" class="btn btn-success">Crear MediEfecSecu</a>
      {% for medi_efec_secu in MediEfecSecus %}
        <tr>
          <td>{{ medi_efec_secu.id }}</td>
          <td>{{ medi_efec_secu.medicamento.nombre }}</td>
          <td>{{ medi_efec_secu.efectosSecundarios.nombre }}</td>
          <td>{{ medi_efec_secu.efectosSecundarios.descripcion }}</td>
          <td>
            <a href="{% url 'core:detail_medi_efec_secu' medi_efec_secu.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_medi_efec_secu' medi_efec_secu.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_medi_efec_secu' medi_efec_secu.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_medico.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Médicos
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      <th>Cédula</th>
      <th>Número de Teléfono</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_medico' %}" class="btn btn-success">Crear Médico</a>
      {% for medico in Medicos %}
        <tr>
          <td>{{ medico.id }}</td>
          <td>{{ medico.nombrePila }}</td>
          <td>{{ medico.apPat }}</td>
          <td>{{ medico.apMat }}</td>
          <td>{{ medico.cedula }}</td>
          <td>{{ medico.numTel }}</td>
          <td>
            <a href="{% url 'core:detail_medico' medico.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_medico' medico.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_medico' medico.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/list_puesto.html
{% extends "base/base.html" %}

{% block title %}
  Lista de Puestos
{% endblock title %}

{% block content %}
  <table class="table table-hover">
    <thead>
      <th>ID</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Acciones</th>
    </thead>
    <tbody>
      <a href="{% url 'core:create_puesto' %}" class="btn btn-success">Crear Puesto</a>
      {% for puesto in Puestos %}
        <tr>
          <td>{{ puesto.id }}</td>
          <td>{{ puesto.nombre }}</td>
          <td>{{ puesto.descripcion }}</td>
          <td>
            <a href="{% url 'core:detail_puesto' puesto.id %}" class="btn btn-info">Detalles</a>
            <a href="{% url 'core:update_puesto' puesto.id %}" class="btn btn-warning">Editar</a>
            <a href="{% url 'core:delete_puesto' puesto.id %}" class="btn btn-danger">Eliminar</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

avance2/controlmedico/core/templates/core/update_forma_administracion.html
{% extends "base/base.html" %}

{% block title %}
  Actualizar Forma de Administración
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'core:list_forma_administracion' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock content %}