avance2/controlmedico/controlmedico/urls.py
from django.contrib import admin
from django.urls import include, path
from home.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include('core.urls')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView, name='logout'),
]

avance2/controlmedico/core/urls.py
from django.urls import path
from . import views
from .views import CreateMedico, ListMedico


app_name = 'core' 

urlpatterns = [
    # URLs para Puesto
    path('puesto/create/', views.CreatePuesto.as_view(), name='create_puesto'),
    path('puesto/list/', views.ListPuesto.as_view(), name='list_puesto'),
    path('puesto/<int:pk>/', views.DetailPuesto.as_view(), name='detail_puesto'),
    path('puesto/update/<int:pk>/', views.UpdatePuesto.as_view(), name='update_puesto'),
    path('puesto/<int:pk>/delete/', views.DeletePuesto.as_view(), name='delete_puesto'),

    # URLs para Empleado
    path('empleado/create/', views.CreateEmpleado.as_view(), name='create_empleado'),
    path('empleado/list/', views.ListEmpleado.as_view(), name='list_empleado'),
    path('empleado/<int:pk>/', views.DetailEmpleado.as_view(), name='detail_empleado'),
    path('empleado/<int:pk>/update/', views.UpdateEmpleado.as_view(), name='update_empleado'),
    path('empleado/<int:pk>/delete/', views.DeleteEmpleado.as_view(), name='delete_empleado'),

    # URLs para Alergia
    path('alergia/create/', views.CreateAlergia.as_view(), name='create_alergia'),
    path('alergia/list/', views.ListAlergia.as_view(), name='list_alergia'),
    path('alergia/<int:pk>/', views.DetailAlergia.as_view(), name='detail_alergia'),
    path('alergia/<int:pk>/update/', views.UpdateAlergia.as_view(), name='update_alergia'),
    path('alergia/<int:pk>/delete/', views.DeleteAlergia.as_view(), name='delete_alergia'),

    # URLs para Departamento
    path('departamento/create/', views.CreateDepartamento.as_view(), name='create_departamento'),
    path('departamento/list/', views.ListDepartamento.as_view(), name='list_departamento'),
    path('departamento/<int:pk>/', views.DetailDepartamento.as_view(), name='detail_departamento'),
    path('departamento/<int:pk>/update/', views.UpdateDepartamento.as_view(), name='update_departamento'),
    path('departamento/<int:pk>/delete/', views.DeleteDepartamento.as_view(), name='delete_departamento'),

    # URLs para Medicamento
    path('medicamento/create/', views.CreateMedicamento.as_view(), name='create_medicamento'),
    path('medicamento/list/', views.ListMedicamento.as_view(), name='list_medicamento'),
    path('medicamento/<int:pk>/', views.DetailMedicamento.as_view(), name='detail_medicamento'),
    path('medicamento/<int:pk>/update/', views.UpdateMedicamento.as_view(), name='update_medicamento'),
    path('medicamento/<int:pk>/delete/', views.DeleteMedicamento.as_view(), name='delete_medicamento'),
    
    # URLs para Suministro
    path('suministro/create/', views.CreateSuministro.as_view(), name='create_suministro'),
    path('suministro/list/', views.ListSuministro.as_view(), name='list_suministro'),
    path('suministro/<int:pk>/', views.DetailSuministro.as_view(), name='detail_suministro'),
    path('suministro/<int:pk>/update/', views.UpdateSuministro.as_view(), name='update_suministro'),
    path('suministro/<int:pk>/delete/', views.DeleteSuministro.as_view(), name='delete_suministro'),

    # URLs para Medico
    path('medico/create/', views.CreateMedico.as_view(), name='create_medico'),
    path('medico/list/', views.ListMedico.as_view(), name='list_medico'),
    path('medico/<int:pk>/', views.DetailMedico.as_view(), name='detail_medico'),
    path('medico/<int:pk>/update/', views.UpdateMedico.as_view(), name='update_medico'),
    path('medico/<int:pk>/delete/', views.DeleteMedico.as_view(), name='delete_medico'),

    # URLs para Consulta
    path('consulta/create/', views.CreateConsulta.as_view(), name='create_consulta'),
    path('consulta/list/', views.ListConsulta.as_view(), name='list_consulta'),
    path('consulta/<int:pk>/', views.DetailConsulta.as_view(), name='detail_consulta'),
    path('consulta/<int:pk>/update/', views.UpdateConsulta.as_view(), name='update_consulta'),
    path('consulta/<int:pk>/delete/', views.DeleteConsulta.as_view(), name='delete_consulta'),
    
    # URLs para EfectosSecundarios
    path('efectos_secundarios/create/', views.CreateEfectosSecundarios.as_view(), name='create_efectos_secundarios'),
    path('efectos_secundarios/list/', views.ListEfectosSecundarios.as_view(), name='list_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/', views.DetailEfectosSecundarios.as_view(), name='detail_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/update/', views.UpdateEfectosSecundarios.as_view(), name='update_efectos_secundarios'),
    path('efectos_secundarios/<int:pk>/delete/', views.DeleteEfectosSecundarios.as_view(), name='delete_efectos_secundarios'),

    # URLs para Contraindicacion
    path('contraindicacion/create/', views.CreateContraindicacion.as_view(), name='create_contraindicacion'),
    path('contraindicacion/list/', views.ListContraindicacion.as_view(), name='list_contraindicacion'),
    path('contraindicacion/<int:pk>/', views.DetailContraindicacion.as_view(), name='detail_contraindicacion'),
    path('contraindicacion/<int:pk>/update/', views.UpdateContraindicacion.as_view(), name='update_contraindicacion'),
    path('contraindicacion/<int:pk>/delete/', views.DeleteContraindicacion.as_view(), name='delete_contraindicacion'),
    # URLs para FormaAdministracion
    path('forma_administracion/create/', views.CreateFormaAdministracion.as_view(), name='create_forma_administracion'),
    path('forma_administracion/list/', views.ListFormaAdministracion.as_view(), name='list_forma_administracion'),
    path('forma_administracion/<int:pk>/', views.DetailFormaAdministracion.as_view(), name='detail_forma_administracion'),
    path('forma_administracion/<int:pk>/update/', views.UpdateFormaAdministracion.as_view(), name='update_forma_administracion'),
    path('forma_administracion/<int:pk>/delete/', views.DeleteFormaAdministracion.as_view(), name='delete_forma_administracion'),

    # URLs para AlergiaEmpleado
    path('alergiaempleado/create/', views.CreateAlergiaEmpleado.as_view(), name='create_alergiaempleado'),
    path('alergiaempleado/list/', views.ListAlergiaEmpleado.as_view(), name='list_alergiaempleado'),
    path('alergiaempleado/<int:pk>/', views.DetailAlergiaEmpleado.as_view(), name='detail_alergiaempleado'),
    path('alergiaempleado/<int:pk>/update/', views.UpdateAlergiaEmpleado.as_view(), name='update_alergiaempleado'),
    path('alergiaempleado/<int:pk>/delete/', views.DeleteAlergiaEmpleado.as_view(), name='delete_alergiaempleado'),

    # URLs para MediEfecSecu
    path('medi_efec_secu/create/', views.CreateMediEfecSecu.as_view(), name='create_medi_efec_secu'),
    path('medi_efec_secu/list/', views.ListMediEfecSecu.as_view(), name='list_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/', views.DetailMediEfecSecu.as_view(), name='detail_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/update/', views.UpdateMediEfecSecu.as_view(), name='update_medi_efec_secu'),
    path('medi_efec_secu/<int:pk>/delete/', views.DeleteMediEfecSecu.as_view(), name='delete_medi_efec_secu'),

    # URLs para MediContra
    path('medi_contra/create/', views.CreateMediContra.as_view(), name='create_medi_contra'),
    path('medi_contra/list/', views.ListMediContra.as_view(), name='list_medi_contra'),
    path('medi_contra/<int:pk>/', views.DetailMediContra.as_view(), name='detail_medi_contra'),
    path('medi_contra/<int:pk>/update/', views.UpdateMediContra.as_view(), name='update_medi_contra'),
    path('medi_contra/<int:pk>/delete/', views.DeleteMediContra.as_view(), name='delete_medi_contra'),

    # URLs para MediFormaAdmi
    path('medi_forma_admi/create/', views.CreateMediFormaAdmi.as_view(), name='create_medi_forma_admi'),
    path('medi_forma_admi/list/', views.ListMediFormaAdmi.as_view(), name='list_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/', views.DetailMediFormaAdmi.as_view(), name='detail_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/update/', views.UpdateMediFormaAdmi.as_view(), name='update_medi_forma_admi'),
    path('medi_forma_admi/<int:pk>/delete/', views.DeleteMediFormaAdmi.as_view(), name='delete_medi_forma_admi'),

    # URLs para SuministroConsulta
    path('suministro_consulta/create/', views.CreateSuministroConsulta.as_view(), name='create_suministro_consulta'),
    path('suministro_consulta/list/', views.ListSuministroConsulta.as_view(), name='list_suministro_consulta'),
    path('suministro_consulta/<int:pk>/', views.DetailSuministroConsulta.as_view(), name='detail_suministro_consulta'),
    path('suministro_consulta/<int:pk>/update/', views.UpdateSuministroConsulta.as_view(), name='update_suministro_consulta'),
    path('suministro_consulta/<int:pk>/delete/', views.DeleteSuministroConsulta.as_view(), name='delete_suministro_consulta'),

    # URLs para MedicamentoConsulta
    path('medicamento_consulta/create/', views.CreateMedicamentoConsulta.as_view(), name='create_medicamento_consulta'),
    path('medicamento_consulta/list/', views.ListMedicamentoConsulta.as_view(), name='list_medicamento_consulta'),
    path('medicamento_consulta/<int:pk>/', views.DetailMedicamentoConsulta.as_view(), name='detail_medicamento_consulta'),
    path('medicamento_consulta/<int:pk>/update/', views.UpdateMedicamentoConsulta.as_view(), name='update_medicamento_consulta'),
    path('medicamento_consulta/<int:pk>/delete/', views.DeleteMedicamentoConsulta.as_view(), name='delete_medicamento_consulta'),
]
 

avance2/controlmedico/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout'),
]

avance2/controlmedico/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta


# Create your models here.

class Alergia(models.Model):
    nombre = models.CharField(max_length=100, null=True)
    descripcion = models.TextField(max_length=255, null=True)

    def __str__(self):
        return self.nombre

class Puesto(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=50, null=True)

    def __str__(self):
        return self.nombre

class Departamento(models.Model):
    nombre = models.CharField(max_length=50, null=True)
    descripcion = models.TextField(max_length=70, null=True)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    nombrePila = models.CharField(max_length=20, null=True)
    apPat = models.CharField(max_length=20, null=True)
    apMat = models.CharField(max_length=20, null=True)
    fnacimiento = models.DateField()
    noempleado = models.CharField(max_length=10, null=True)
    puesto = models.ForeignKey('Puesto', on_delete=models.CASCADE)
    departamento = models.ForeignKey('Departamento', on_delete=models.CASCADE, default='')

    alergias = models.ManyToManyField('Alergia', through='AlergiaEmpleado')

    def __str__(self):
        return f"{self.noempleado} {self.nombrePila} {self.apPat} {self.apMat} "

class Medicamento(models.Model):
    nombre = models.CharField(max_length=40)
    descripcion = models.TextField(max_length=40)
    dosis = models.IntegerField()
    stock = models.IntegerField()

    efectos_secundarios = models.ManyToManyField('EfectosSecundarios', through='MediEfecSecu')
    contraindicaciones = models.ManyToManyField('Contraindicacion', through='MediContra')
    formas_administracion = models.ManyToManyField('FormaAdministracion', through='MediFormaAdmi')

    def __str__(self):
        return self.nombre

class Suministro(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=50)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre

class Medico(models.Model):
    nombrePila = models.CharField(max_length=20)
    apPat = models.CharField(max_length=20, null=True)
    apMat = models.CharField(max_length=20, null=True)
    cedula = models.CharField(max_length=10, null=True)
    numTel = models.BigIntegerField()

    def __str__(self):
        return self.nombrePila

class Consulta(models.Model):
    fecha = models.DateField()
    edad = models.IntegerField()
    motivo = models.CharField(max_length=255, null=True)
    sintomas = models.CharField(max_length=255, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=2)
    altura = models.DecimalField(max_digits=5, decimal_places=2)
    diagnostico = models.CharField(max_length=255, null=True)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)
    medico = models.ForeignKey('Medico', on_delete=models.CASCADE)

    medicamentos = models.ManyToManyField('Medicamento', through='MedicamentoConsulta')
    suministros = models.ManyToManyField('Suministro', through='SuministroConsulta')

    def __str__(self):
        return str(self.id)

class EfectosSecundarios(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class Contraindicacion(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class FormaAdministracion(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)

    def __str__(self):
        return self.nombre

class AlergiaEmpleado(models.Model):
    alergia = models.ForeignKey('Alergia', on_delete=models.CASCADE)
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.alergia)

class SuministroConsulta(models.Model):
    suministro = models.ForeignKey('Suministro', on_delete=models.CASCADE)
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default='1')

    def __str__(self):
        return f"{self.suministro} - {self.consulta}"

class MedicamentoConsulta(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    consulta = models.ForeignKey('Consulta', on_delete=models.CASCADE)
    cantidad = models.IntegerField(default='1')

    def __str__(self):
        return f"{self.medicamento} - {self.consulta}"
    
class MediEfecSecu(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    efectosSecundarios = models.ForeignKey('EfectosSecundarios', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

class MediContra(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    contraindicaciones = models.ForeignKey('Contraindicacion', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

class MediFormaAdmi(models.Model):
    medicamento = models.ForeignKey('Medicamento', on_delete=models.CASCADE)
    formaAdministracion = models.ForeignKey('FormaAdministracion', on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30, null=True)

    def __str__(self):
        return str(self.medicamento)

avance2/controlmedico/core/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <!-- NAV BAR -->
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">CONTROL MEDICO</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item"> 
                            <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_puesto' %}">Puestos</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_empleado' %}">Empleados</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_alergia' %}">Alergias</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_departamento' %}">Departamento</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_medicamento' %}">Medicamento</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_suministro' %}">Suministros</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_medico' %}">Medicos</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_consulta' %}">Consultas</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_efectos_secundarios' %}">Efectos Secundarios</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_contraindicacion' %}">Contraindicaciones</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_forma_administracion' %}">Forma Administracion</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_alergiaempleado' %}">Alergias Empleados</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_medi_efec_secu' %}">Medicamentos Efectos Secundarios</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'core:list_medi_contra' %}">Medicamentos Contraindicaciones</a>
                          </li>
                            <a class="nav-link" href="{% url 'core:list_medi_forma_admi' %}">Medicamentos Forma Administracion</a>
                          </li>
                          </li>
                            <a class="nav-link" href="{% url 'core:list_suministro_consulta' %}">Suministro Consulta</a>
                          </li>
                          </li>
                          <a class="nav-link" href="{% url 'core:list_medicamento_consulta' %}">Medicamento Consulta</a>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2"></div>
            <div class "col-8">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-2"></div>
        </div>
        <div class="row">
            <div class="col">
                <footer class="text-center text-white" style="background-color: #f1f1f1;">
                    <!-- Grid container -->
                    <div class="container pt-4">
                      <!-- Section: Social media -->
                      <section class="mb-4">
                        <!-- Facebook -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-facebook-f"></i
                        ></a>
                  
                        <!-- Twitter -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-twitter"></i
                        ></a>

                        <i class="glyphicon glyphicon-cloud"></i>

                  
                        <!-- Google -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-google"></i
                        ></a>
                  
                        <!-- Instagram -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-instagram"></i
                        ></a>
                  
                        <!-- Linkedin -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-linkedin"></i
                        ></a>
                        <!-- Github -->
                        <a
                          class="btn btn-link btn-floating btn-lg text-dark m-1"
                          href="#!"
                          role="button"
                          data-mdb-ripple-color="dark"
                          ><i class="fab fa-github"></i
                        ></a>
                      </section>
                      <!-- Section: Social media -->
                    </div>
                    <!-- Grid container -->
                  
                    <!-- Copyright -->
                    <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                      © 2023 Copyright:
                      <a class="text-dark" href="Rodriguez Altamirano Christian Rodolfo">Rodriguez Altamirano Christian Rodolfo</a>
                    </div>
                    <!-- Copyright -->
                  </footer>
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>